#!/usr/bin/env bash
set -euo pipefail

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
# Reset
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;37m'  # White

# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

# Background
On_Black='\033[40m'  # Black
On_Red='\033[41m'    # Red
On_Green='\033[42m'  # Green
On_Yellow='\033[43m' # Yellow
On_Blue='\033[44m'   # Blue
On_Purple='\033[45m' # Purple
On_Cyan='\033[46m'   # Cyan
On_White='\033[47m'  # White

# High Intensity
IBlack='\033[0;90m'  # Black
IRed='\033[0;91m'    # Red
IGreen='\033[0;92m'  # Green
IYellow='\033[0;93m' # Yellow
IBlue='\033[0;94m'   # Blue
IPurple='\033[0;95m' # Purple
ICyan='\033[0;96m'   # Cyan
IWhite='\033[0;97m'  # White

# Bold High Intensity
BIBlack='\033[1;90m'  # Black
BIRed='\033[1;91m'    # Red
BIGreen='\033[1;92m'  # Green
BIYellow='\033[1;93m' # Yellow
BIBlue='\033[1;94m'   # Blue
BIPurple='\033[1;95m' # Purple
BICyan='\033[1;96m'   # Cyan
BIWhite='\033[1;97m'  # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'  # Black
On_IRed='\033[0;101m'    # Red
On_IGreen='\033[0;102m'  # Green
On_IYellow='\033[0;103m' # Yellow
On_IBlue='\033[0;104m'   # Blue
On_IPurple='\033[0;105m' # Purple
On_ICyan='\033[0;106m'   # Cyan

# end
NC='\033[0m'

color_cyan() {
    echo -e "${Cyan}$1${NC}"
}
color_purple() {
    echo -e "${Purple}$1${NC}"
}
color_white() {
    echo -e "${White}$1${NC}"
}
color_green() {
    echo -e "${Green}$1${NC}"
}
color_red() {
    echo -e "${Red}$1${NC}"
}
color_yellow() {
    echo -e "${Yellow}$1${NC}"
}
color_warn() {
    color_yellow "$1"
}
color_out() {
    color_white "$1"
}
color_error() {
    color_red "$1"
}
color_info() {
    color_green "$1"
}
color_sub() {
    color_cyan "$1"
}

color_bg_purple() {
    echo -e "${On_Purple}$1${NC}"
}

color_bg_cyan() {
    echo -e "${On_Cyan}$1${NC}"
}

color_bg_green() {
    echo -e "${On_Green}$1${NC}"
}

color_bg_red() {
    echo -e "${On_Red}$1${NC}"
}

color_bg_yellow() {
    echo -e "${On_Yellow}$1${NC}"
}

error_less_arg() {
    color_error "> 错误：缺少必须参数，请检查输入。"
}

if [ $# -eq 1 ] && [ $1 = 'test' ]; then
    for ((i = 30; i < 38; i++)); do
        echo -e "\033[0;"$i"m Normal: (0;$i); \033[1;"$i"m Light: (1;$i)"
    done
fi
