#!/usr/bin/env bash
set -euo pipefail

source $GCLRC_SHELL/colors

BIN="/usr/local/bin"

name="$(uname)"

test_command() {
    local ret='0'
    command -v $1 >/dev/null 2>&1 || { local ret='1'; }

    # fail on non-zero return value
    if [ "$ret" -ne 0 ]; then
        if [ "$2" ]; then
            color_info "$2 $1"
            $($2 $1)
        fi

        return 1
    fi
    color_warn "> command $1 existed > $(which $1)"

    return 0
}

test_dir() {
    if [ ! -d "$1" ]; then
        mkdir -p "$1"
    else
        color_warn "> Directory: $1 已存在。"
    fi
}

test_dir_rm() {
    if [ -d "$1" ]; then
        rm -rf "$1"
    fi
}

link_s_bin_full() {
    name="$1"
    src="$2"
    if [ ! -f "$BIN/$name" ] && [ -f "$src" ]; then
        ln -s "$src" "$BIN/$name"
    else
        color_warn "> $BIN/$name 已存在."
    fi
}
link_s_bin() {
    cmd="$1"
    path="$2"
    link_s_bin_full "$cmd" "$path/$cmd"
}

brew_install() {
    color_info "> brew install $1"
    test_command "$1" "brew install"
}

brew_install_cask() {
    color_info "> brew install --cask $1"
    test_command "$1" "brew install --cask"
}

pipx_install() {
    color_info "> pipx install $1"
    test_command "$1" "pipx install"
}

if [ -f /etc/os-release ]; then
    source /etc/os-release
fi

is_mac() {
    if [ "$(uname)" == "Darwin" ]; then return 0; else return 1; fi
}

is_ubuntu() {
    if [ "$NAME" == "Ubuntu" ]; then return 0; else return 1; fi
}

git_clone_lib() {
    target_dir="$1"
    code_url="$2"
    depth=""
    if [ $# -eq 3 ] && [ "$3" == "depth" ]; then
        depth="--depth=1"
    fi
    if [ -d "$target_dir" ]; then
        color_warn "> $target_dir existed, ready to update..."
        cd "$target_dir" && git pull
    else
        git clone $depth $code_url $target_dir
    fi

}

git_clone_depth1() {
    git_clone_lib "$1" "$2" depth
}

cp_dir_files() {
    src="$1"
    dir="$2"
    if [ ! -d "$src" ] || [ ! -d "$dir" ]; then
        echo "src or target is not a directory."
        exit -1
    fi

    cd $src
    for file in *; do
        target="$dir/$file"
        if [ -f "$target" ]; then
            continue
        fi

        if [ -f "$file" ]; then
            cp $file $target
        fi
    done
    echo "DONE."

}

echo-link() {
    if [ $# -lt 1 ]; then
        color_red "Link URL required!"
        exit -1
    fi
    url="$1"
    hint=""
    if [ $# -lt 2 ]; then
        hint="$url"
    else
        hint="$2"
    fi

    printf '\033[4;32m\e]8;;'$url'\e\\'$hint'\e]8;;\e\\\033[0m\n'
}
