# -*- mode: conf -*-
# ======================== M alias ========================

alias minfo='echo "=== alias m ==="
echo ""
echo "-- m, mac CLI, https://github.com/guarinogabriel/Mac-CLI"
echo "   mcat           = mac categories            命令分类"
echo "   mupdate        = mac update                更新系统软件"
echo "   muself         = mac upgrade               更新 mac 自身到最新版本"
echo "   muinstall      = mac uninstall             卸载 mac CLI"
echo "   mlock          = mac lock                  锁定电脑"
echo "   mres           = mac restart               重启电脑"
echo "   msleep         = mac sleep                 休眠"
echo "   mshutd         = mac shutdown              关机"
echo "   mprepare       = mac presentation          修复电脑"
echo "   mtime          = mac time                  在终端上方显示时间"
echo "   mvol           = mac volume <x>            设置音量"
echo "   mvolm          = mac volume:mute           静音"
echo "   mvolmu         = mac volume:umute          取消静音"
echo "   mflist         = mac folders:list          显示当前目录下的目录及其大小"
echo "   mfsize         = mac folder:size           计算当前目录大小"
echo "   mfempty        = mac folders:remove-empty  删除空目录"
echo "   mclose         = mac apps:close-all        关闭所有已打开的应用"
echo "   mlstore        = mac apps:app-store        列出从 App Store 安装的所有应用"
echo "   meject         = mac eject-all             弹出所有已挂载的 volumes 和 disks"
echo "   mbattery       = mac battery               电池信息"
echo ""
echo "   - ssh"
echo "   msync-local    = mac ssh:sync:local"
echo "   msync-remote   = mac ssh:sync:remote"
echo "   mupload        = mac ssh:upload"
echo "   mdfile         = mac ssh:download-file"
echo "   mdfolder       = mac ssh:download-folder"
echo "   mddb           = mac ssh:download-database"
echo "   mdimg          = mac web:download-images"
echo ""
echo "   - 查找替换"
echo "   mfr            = mac find:recent"
echo "   msr            = mac search:replace"
echo "   mftext         = mac find:text <string>        在当前目录下递归查找指定字符串"
echo "   mfbigest       = mac find:biggest-files        在当前目录下查找最大的文件"
eche "   mfdigest       = mac find:biggest-directories  在当前目录下查找最大的目录"
echo "   mzipx          = mac zip:extract <f.zip>       解压 x.zip"
echo "   mgzip          = mac gzip:compress <file>      压缩成 gzip"
echo "   mgzipx         = mac gzip:extract <dir>        解压 x.gzip"
echo "   mtar           = mac tar:compress <file|dir>   压缩成 tar"
echo "   mtarx          = mac tar:extract <file|dir>    解压 x.tar"

echo ""
echo "   - 系统相关"
echo "   msys           = mac system                系统信息"
echo "   mtmp           = mac temp                  临时文件"
echo "   mem            = mac memory                内存信息"
echo "   mctrash        = mac trash:empty"
echo "   mcdesktop      = mac desktop:cleanup"
echo "   mcdownload     = mac downloads:cleanup"
echo "   mcxcode        = mac xcode:cleanup         清理 xcode 垃圾"
echo ""
echo "   - 网络"
echo "   mspeed         = mac speedtest             测速"
echo "   mspeedi        = mac speedtest:infinite    五分钟执行一次"
echo "   mports         = mac ports                 查看端口"
echo "   miplocal       = mac ip:local              查看IP"
echo "   mipublic       = mac ip:public             查看IP"
echo "   mdhcprn        = mac dhcp:renew"
echo "   mcdns          = mac dns:clear"
echo ""
echo "   - LAMP, MAMP, Linux+Apache+MySql+PHP"
echo "   msql           = mac mysql"
echo "   mmcli          = mac mysql:cli"
echo "   mmlist         = mac mysql:list"
echo "   mmexp          = mac mysql:export"
echo "   mmexpa         = mac mysql:export-all"
echo "   mmimp          = mac mysql:import"
echo "   mmimptbl       = mac mysql:import-table"
echo "   mmcreate       = mac mysql:create"
echo "   mmdrop         = mac mysql:drop"
echo "   mmdup          = mac mysql:duplicate"
echo "   mastart        = mac mamp:start"
echo "   mastop         = mac mamp:stop"
echo "   marestart      = mac mamp:restart"
echo ""
echo "   - php"
echo "   mpsyntax       = mac mamp:restart"
echo "   mpinfo         = mac php:info"
echo "   mehosts        = mac hosts:edit            编辑 /etc/hosts"
echo ""
echo "   - image"
echo "   mimage         = mac image:generate:mobile-app-icons <源图片地址> <输出图片目录>"
echo ""
echo "   - brew"
echo "   mbrewu         = mac brew:update"
echo ""
echo "   - git"
echo "   mgconfig       = mac git:config"
echo "   mgopen         = mac git:open"
echo "   mgcb           = mac git:create:branch     创建新分支"
echo "   mguc           = mac git:undo-commit"
echo "   mglog          = mac git:log"
echo "   mgar           = mac git:add-removed"
echo "   mgsize         = mac git:size"
echo "   mgbranch       = mac git:branch"
echo "   mgbd           = mac git:branches:date"
echo "   mgbr           = mac git:branch:rename"
echo "   mgbdl          = mac git:branch:remove-local"
echo "   mgbdr          = mac git:branch:remove-remote"
echo ""
echo "   - development"
echo "   mdm            = mac dev:monitor X: Monitor file changes (for example: log file) - X = File to monitor"
echo "   mdoi           = mac dev:optimize-images: Optimize all images in current directory and subdirectories"
echo "   mdcs           = mac dev:css:convert-to-scss: Convert CSS file to SCSS"
echo "------------------------------------------------------------"
echo ""
'

# mac cli: https://github.com/guarinogabriel/Mac-CLI
alias mcat="mac categories"
# === zip, tar, gzip
alias mupdate="mac update"
alias muself="mac upgrade"
alias muinstall="mac uninstall"
alias mlock="mac lock"
alias mreboot="mac restart"
alias msleep="mac sleep"
alias mshutd="mac shutdown"
alias mprepare="mac presentation"
alias mtime="mac time"
alias mvol="mac volume"
alias mvolm="mac volume:mute"
alias mvolmu="mac volume:umute"
alias mflist="mac folders:list"
alias mfsize="mac folder:size"
alias mfempty="mac folders:remove-empty"
alias mclose="mac apps:close-all"
alias mlstore="mac apps:app-store"
alias meject="mac eject-all"
alias mbattery="mac battery"

# === SSH Utilities:
alias msync-local="mac ssh:sync:local"
alias msync-remote="mac ssh:sync:remote"
alias mupload="mac ssh:upload"
alias mdfile="mac ssh:download-file"
alias mdfolder="mac ssh:download-folder"
alias mddb="mac ssh:download-database"
alias mdimg="mac web:download-images"
# === Search Utilities:
# cmd 1, search last 1 minutes recent
alias mfr="mac find:recent"
alias msr="mac search:replace"

# === Performance and maintenance Utilities:
alias msys="mac system"
alias mtmp="mac temp"
alias mem="mac memory"
alias mctrash="mac trash:empty"
alias mcdesktop="mac desktop:cleanup"
alias mcdownload="mac downloads:cleanup"
alias mcxcode="mac xcode:cleanup"

# === Network:
alias mspeed="mac speedtest"
alias mspeedi="mac speedtest:infinite"  # 每五分钟执行一次
alias mports="mac ports"
alias miplocal="mac ip:local"
alias mipublic="mac ip:public"
alias mdhcprn="mac dhcp:renew"
alias mcdns="mac dns:clear"

# === LAMP
alias msql="mac mysql"
alias mmcli="mac mysql:cli"
alias mmlist="mac mysql:list"
alias mmexp="mac mysql:export"
alias mmexpa="mac mysql:export-all"
alias mmimp="mac mysql:import"
alias mmimptbl="mac mysql:import-table"
alias mmcreate="mac mysql:create"
alias mmdrop="mac mysql:drop"
alias mmdup="mac mysql:duplicate"
alias mastart="mac mamp:start"
alias mastop="mac mamp:stop"
alias marestart="mac mamp:restart"
alias mpsyntax="mac php:syntax"
alias mpinfo="mac php:info"
alias mehosts="mac hosts:edit"

# === Image
# x y, x - 源图片地址，y - 输出图片地址
alias mimage="mac image:generate:mobile-app-icons"

# === Brew
alias mbrewu="mac brew:update"

# === Git
alias mgconfig="mac git:config"
alias mgopen="mac git:open"
alias mgcb="mac git:create:branch"
alias mguc="mac git:undo-commit"
alias mglog="mac git:log"
alias mgar="mac git:add-removed"
alias mgsize="mac git:size"
alias mgbranch="mac git:branch"
alias mgbd="mac git:branches:date"
alias mgbrename="mac git:branch:rename"
alias mgbdlocal="mac git:branch:remove-local"
alias mgbdremote="mac git:branch:remove-remote"

# === Development
alias mdmonitor="mac dev:monitor"
alias mdoi="mac dev:optimize-images"
alias mdcs="mac dev:css:convert-to-scss"

# mu4e
alias musync="time mbsync -a"
alias musidx="musync && mu index"
