#+TITLE: Recipies
* Unsorted
** Homemade Black Bean Veggie Burgers
:PROPERTIES:
:source-url: http://allrecipes.com/recipe/85452/homemade-black-bean-veggie-burgers/
:servings: 4 patties
:prep-time: 15 minutes
:cook-time: 20 minutes
:ready-in: 35 minutes
:END:
*** Ingredients

- 1 (16 ounce) can black beans, drained and rinsed
- ½ green bell pepper, cut into 2 inch pieces
- ½ onion, cut into wedges
- 3 cloves garlic, peeled
- 1 egg
- 1 tablespoon chili powder
- 1 tablespoon cumin
- 1 teaspoon Thai chili sauce or hot sauce
- ½ cup bread crumbs
*** Directions

1. If grilling, preheat an outdoor grill for high heat, and lightly oil a sheet of aluminum foil. If baking, preheat oven to 375 degrees F (190 degrees C), and lightly oil a baking sheet.
2. In a medium bowl, mash black beans with a fork until thick and pasty.
3. In a food processor, finely chop bell pepper, onion, and garlic. Then stir into mashed beans.
4. In a small bowl, stir together egg, chili powder, cumin, and chili sauce.
5. Stir the egg mixture into the mashed beans. Mix in bread crumbs until the mixture is sticky and holds together. Divide mixture into four patties.
6. If grilling, place patties on foil, and grill about 8 minutes on each side. If baking, place patties on baking sheet, and bake about 10 minutes on each side.
